---
title: "Novel Covid-19 dataset from John Hopkins"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
```{r}
countries_aggregated = read.csv("data/countries-aggregated.csv")
key_countries_pivoted = read.csv("data/key-countries-pivoted.csv")
reference = read.csv("data/reference.csv")
time_series_19_covid_combined = read.csv("data/time-series-19-covid-combined.csv")
us_confirmed = read.csv("data/us_confirmed.csv")
us_deaths = read.csv("data/us_deaths.csv")
worldwide_aggregated = read.csv("data/worldwide-aggregated.csv")
world_cities = read.csv("data/worldcities.csv")
Statewide = read.csv("data/Statewide (1).csv")
```

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(plotly)
library(leaflet)
library(sp)
library(flexdashboard)
library(broom)
library(modelr)
```
Page 1
===================================== 
Column {data-width=650}
-----------------------------------------------------------------------

### Chart A
```{r}
us_confirmed_updated = us_confirmed %>%
  group_by(Province.State) %>%
  summarize(
    Lat = mean(Lat),
    Long = mean(Long),
    total_cases = sum(Case)
  )
  
```

```{r}
us_confirmed_updated %>%
    leaflet() %>%
    addProviderTiles("OpenStreetMap.Mapnik") %>%
    addMarkers(
      lng = ~Long,
      lat = ~Lat,
      popup = ~paste("</h3><br>","State:", Province.State, "</h3><br>","Cases:", total_cases,  sep=" "))
```

Column {.tabset}
-----------------------------------------------------------------------

### Chart B

```{r}
ggplotly(us_confirmed_updated %>%
  ggplot() + geom_col(mapping=aes(x=Province.State, y=total_cases), fill="Blue")+ theme_gray()+ labs(title = "Total cases in each US State")+ylab("Cases")+xlab("State") +theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)))
```

### Chart C

```{r}
Statewide_updated = Statewide %>%
  arrange(Effective.Date)
ggplotly(Statewide_updated %>%
  ggplot() + geom_col(mapping=aes(x=State, y=fct_rev(as_factor(Effective.Date))), fill="Lightblue")+theme_dark()+labs(title = " Statewide Stay at Home Orders by Date") +ylab("Date")+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)))
```



### Chart D
```{r}
reference_updated = reference %>%  drop_na() %>%
    group_by(Province.State) %>%
    summarize(
      total_pop = sum(Population)
    )
ggplotly(reference_updated %>%
  ggplot() + geom_col(mapping=aes(x=Province.State, y=total_pop), fill="Green")+ theme_minimal()+ labs(title="State population")+ylab("Population")+xlab("State")+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)))
  
```
Column {data-width=650}
-----------------------------------------------------------------------

Page 2
===================================== 
Column {data-width=650}
-----------------------------------------------------------------------
### Chart A
```{r}
us_confirmed_updated1 = us_confirmed %>%
  group_by(Province.State) %>%
  summarize(
    total_cases = sum(Case)
  )
  
```
 

```{r}
library(dplyr)
us_confirmed_pop = reference_updated %>% inner_join(us_confirmed_updated1 , by="Province.State")
```


```{r}
confirmed_pop_model = lm(total_cases~total_pop, data=us_confirmed_pop)
```

```{r}
confirmed_pop_df = us_confirmed_pop %>%
  add_predictions(confirmed_pop_model)%>%
  add_residuals(confirmed_pop_model)
```




```{r}
ggplot(confirmed_pop_df) +
  geom_point(mapping = aes(x = pred, y = total_cases)) +
  geom_abline(slope = 1, intercept = 0, color="red")
```

### Chart B

```{r}
confirmed_pop_df %>%
  ggplot()+geom_histogram(mapping=aes(x=resid), bins=30)
```

Column {data-width=650}
-----------------------------------------------------------------------

```{r}
confirmed_pop_model %>%
  glance()
```
```{r}
confirmed_pop_model %>%
  tidy()
```

